# Generated by Django 3.2 on 2025-04-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_videolike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolike',
            name='is_like',
            field=models.BooleanField(),
        ),
    ]
